#!/bin/bash
#Menu Original

wget -O /bin/menu https://raw.githubusercontent.com/rockneters/sshmngr/main/Modulos/menu?token=AVIXXVZUJDTCZ2N3JAKDS6DBGH7NY > /dev/null 2>&1; chmod +x /bin/menu; /bin/menu
#fim
