#!/bin/bash
#Menu Adaptado Completo

wget -O /bin/menu https://raw.githubusercontent.com/rockneters/sshmngr/main/Install/Menu_UP/menuV2/menuV2?token=AVIXXV4MY2RJOME7U2YJ4QLBGH7R2; chmod +x /bin/menu; /bin/menu
#fim
